version: '3.4'

services:
  booking-api:
    image: booking-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=booking
    ports:
      - 5432:5432
    volumes:
      - ../pgdata:/var/lib/postgresql/data
